name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * 1"   # runs every Monday at midnight
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Tazahnae
          outputs: |
            dist/snake.svg

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
