name: Generate Snake Animation

# Give this workflow permission to push a branch
permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * 1"      # every Monday at 00:00 UTC
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Tazahnae
          outputs: |
            dist/snake.svg

      - name: Deploy to output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output      # target branch
          folder: dist        # folder containing snake.svg
          clean: true
